var onError = function (error) {
    //    console.log('Inside Errors Handler');

    //    console.error('Following error occurred: ', error);
}

module.exports = onError;